#!/bin/sh

YELLOW="\033[1;33m"
NONE="\033[m"

printf $YELLOW
printf "                               _       "
printf "\n  _ __   ___ _ __   __ _ _   _(_)_ __  "
printf "\n | '_ \ / _ \ '_ \ / _\` | | | | | '_ \ "
printf "\n | |_) |  __/ | | | (_| | |_| | | | | |"
printf "\n | .__/ \___|_| |_|\__, |\__,_|_|_| |_|"
printf "\n |_|               |___/               "
printf $NONE
printf "\n\n"
