#!/bin/sh

W="\033[1;37m"
N="\033[m"
G="\033[1;32m"
LR="\033[1;31m"
R="\033[0;32;31m"
Y="\033[1;33m"
LG="\033[1;32m"

printf " * $LR  24  X$W Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz $N\n"
printf " * $LR 128 GB$W 1600 MHz ECC-RAM $N(up to$LG 1TB$N) \n"
printf " * $LR 160 GB$W SSD $N(with$LG 24TB$N NAS) $N \n"

printf "\n"
